{% set name = "polyleven" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/polyleven-{{ version }}.tar.gz
  sha256: d74d348387cf340051711c0dd6af993b4c264daa78470098de16f4a2b725785c

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - polyleven
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ceptord.net/20181215-polyleven.html
  summary: A fast C-implemented library for Levenshtein distance
  license: SAX-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
